=== ktung/cookbook/old/src/assets/recipes/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "http://example.com/example.json",
  "title": "Root Schema",
  "type": "object",
  "default": {},
  "required": ["name", "ingredients", "presetTotalIngredient", "notes"],
  "properties": {
    "name": {
      "title": "The name Schema",
      "type": "object",
      "default": {},
      "required": ["en", "fr"],
      "properties": {
        "en": {
          "title": "The en Schema",
          "type": "string",
          "default": "",
          "examples": ["100 - Burger buns"]
        },
        "fr": {
          "title": "The fr Schema",
          "type": "string",
          "default": "",
          "examples": ["100 - Pains burger"]
        }
      },
      "examples": [
        {
          "en": "100 - Burger buns",
          "fr": "100 - Pains burger"
        }
      ]
    },
    "ingredients": {
      "title": "The ingredients Schema",
      "type": "array",
      "default": [],
      "items": {
        "title": "A Schema",
        "type": "object",
        "required": ["name", "bakerPercentage"],
        "properties": {
          "name": {
            "title": "The name Schema",
            "type": "string",
            "examples": [
              "allPurposeFlour",
              "activeDryYeast",
              "salt",
              "brownSugar",
              "egg",
              "oatMilk",
              "water",
              "butter"
            ]
          },
          "bakerPercentage": {
            "title": "The bakerPercentage Schema",
            "type": ["integer", "number"],
            "examples": [100, 1.6, 1.8, 3, 10, 6, 40]
          }
        },
        "examples": [
          {
            "name": "allPurposeFlour",
            "bakerPercentage": 100
          },
          {
            "name": "activeDryYeast",
            "bakerPercentage": 1.6
          },
          {
            "name": "salt",
            "bakerPercentage": 1.8
          },
          {
            "name": "brownSugar",
            "bakerPercentage": 3
          },
          {
            "name": "egg",
            "bakerPercentage": 10
          },
          {
            "name": "oatMilk",
            "bakerPercentage": 6
          },
          {
            "name": "water",
            "bakerPercentage": 40
          },
          {
            "name": "butter",
            "bakerPercentage": 10
          }
        ]
      },
      "examples": [
        [
          {
            "name": "allPurposeFlour",
            "bakerPercentage": 100
          },
          {
            "name": "activeDryYeast",
            "bakerPercentage": 1.6
          },
          {
            "name": "salt",
            "bakerPercentage": 1.8
          },
          {
            "name": "brownSugar",
            "bakerPercentage": 3
          },
          {
            "name": "egg",
            "bakerPercentage": 10
          },
          {
            "name": "oatMilk",
            "bakerPercentage": 6
          },
          {
            "name": "water",
            "bakerPercentage": 40
          },
          {
            "name": "butter",
            "bakerPercentage": 10
          }
        ]
      ]
    },
    "presetTotalIngredient": {
      "title": "The presetTotalIngredient Schema",
      "type": "integer",
      "default": 0,
      "examples": [862]
    },
    "notes": {
      "title": "The notes Schema",
      "type": "object",
      "default": {},
      "required": [],
      "properties": {
        "fr": {
          "title": "The fr Schema",
          "type": "array",
          "default": [],
          "items": {
            "title": "A Schema",
            "type": "string",
            "default": "",
            "examples": ["1 pain ~= 110g"]
          },
          "examples": [["1 pain ~= 110g"]]
        }
      },
      "examples": [
        {
          "fr": ["1 pain ~= 110g"]
        }
      ]
    }
  },
  "examples": [
    {
      "name": {
        "en": "100 - Burger buns",
        "fr": "100 - Pains burger"
      },
      "ingredients": [
        {
          "name": "allPurposeFlour",
          "bakerPercentage": 100
        },
        {
          "name": "activeDryYeast",
          "bakerPercentage": 1.6
        },
        {
          "name": "salt",
          "bakerPercentage": 1.8
        },
        {
          "name": "brownSugar",
          "bakerPercentage": 3
        },
        {
          "name": "egg",
          "bakerPercentage": 10
        },
        {
          "name": "oatMilk",
          "bakerPercentage": 6
        },
        {
          "name": "water",
          "bakerPercentage": 40
        },
        {
          "name": "butter",
          "bakerPercentage": 10
        }
      ],
      "presetTotalIngredient": 862,
      "notes": {
        "fr": ["1 pain ~= 110g"]
      }
    }
  ]
}

=== ktung/cookbook/old/src/assets/recipes/100-burger-buns.json
{
  "$schema": "./schema.json",
  "name": {
    "en": "100 - Burger buns",
    "fr": "100 - Pains burger"
  },
  "ingredients": [
    {
      "name": "allPurposeFlour",
      "bakerPercentage": 100
    },
    {
      "name": "activeDryYeast",
      "bakerPercentage": 1.6
    },
    {
      "name": "salt",
      "bakerPercentage": 1.8
    },
    {
      "name": "brownSugar",
      "bakerPercentage": 3
    },
    {
      "name": "egg",
      "bakerPercentage": 10
    },
    {
      "name": "oatMilk",
      "bakerPercentage": 6
    },
    {
      "name": "water",
      "bakerPercentage": 40
    },
    {
      "name": "butter",
      "bakerPercentage": 10
    }
  ],
  "presetTotalIngredient": 862,
  "notes": {
    "fr": ["1 pain ~= 110g"]
  }
}

=== ktung/cookbook/old/src/assets/recipes/200-brioche.json
{
  "$schema": "./schema.json",
  "name": {
    "en": "200 - Brioche",
    "fr": "200 - Brioche"
  },
  "ingredients": [
    {
      "name": "allPurposeFlour",
      "bakerPercentage": 100
    },
    {
      "name": "salt",
      "bakerPercentage": 1.8
    },
    {
      "name": "activeDryYeast",
      "bakerPercentage": 1.8
    },
    {
      "name": "brownSugar",
      "bakerPercentage": 12
    },
    {
      "name": "oatMilk",
      "bakerPercentage": 50
    },
    {
      "name": "egg",
      "bakerPercentage": 10
    },
    {
      "name": "butter",
      "bakerPercentage": 30
    }
  ],
  "presetTotalIngredient": 1028,
  "notes": {
    "fr": [
      "Nanterre : 400g (8*50)",
      "Courrone : 400g",
      "Tresse 3 brins : 450g (3*150)",
      "Tresse 1 brin : 70g"
    ]
  }
}

=== ktung/cookbook/src/assets/recipes/100-creme-brulee.json
{
  "$schema": "./schema.json",
  "name": {
    "en": "100 - Creme brulee",
    "fr": "100 - Crème brûlée"
  },
  "ingredients": [
    {
      "name": "cream35",
      "bakerPercentage": 50
    },
    {
      "name": "wholeMilk",
      "bakerPercentage": 50
    },
    {
      "name": "eggYolk",
      "bakerPercentage": 16
    },
    {
      "name": "whiteSugar",
      "bakerPercentage": 8
    }
  ],
  "presetTotalIngredient": 620,
  "notes": {
    "fr": [
      "1 jaune d'oeuf ~= 20g",
      "Cuisson 110°C 1h10 ventilé (mesuré à 15.5°C à froid)",
      "Xg par ramequin",
      "Testé avec 20-23% de jaune d'oeuf",
      "Testé avec 75/25 creme/lait"
    ]
  }
}

=== ktung/cookbook/old/src/assets/recipes/100-financiers.json
{
  "$schema": "./schema.json",
  "name": {
    "en": "100 - Financier",
    "fr": "100 - Financier"
  },
  "ingredients": [
    {
      "name": "eggWhite",
      "bakerPercentage": 100
    },
    {
      "name": "butter",
      "bakerPercentage": 83.3
    },
    {
      "name": "allPurposeFlour",
      "bakerPercentage": 50
    },
    {
      "name": "almondFlour",
      "bakerPercentage": 66.6
    },
    {
      "name": "whiteSugar",
      "bakerPercentage": 111
    }
  ],
  "presetTotalIngredient": 740,
  "notes": {
    "fr": [
      "1 blanc oeuf ~= 30g",
      "Moule rond 60g",
      "Moule rectangle 100g",
      "Cuisson 25-30mins 200C conventionnel"
    ]
  }
}

=== ktung/cookbook/old/src/assets/recipes/100-creme-brulee.json
{
  "$schema": "./schema.json",
  "name": {
    "en": "100 - Creme brulee",
    "fr": "100 - Crème brûlée"
  },
  "ingredients": [
    {
      "name": "cream35",
      "bakerPercentage": 50
    },
    {
      "name": "wholeMilk",
      "bakerPercentage": 50
    },
    {
      "name": "eggYolk",
      "bakerPercentage": 20
    },
    {
      "name": "whiteSugar",
      "bakerPercentage": 8
    }
  ],
  "presetTotalIngredient": 640,
  "notes": {
    "fr": [
      "1 jaune d'oeuf ~= 20g",
      "Cuisson 110°C 1h10 ventilé (mesuré à 15.5°C à froid)",
      "Cuisson 110°C 1h07 conventionel (mesuré à 17.5°C à froid)",
      "106g par ramequin",
      "Testé avec 20-23% de jaune d'oeuf",
      "Testé avec 75/25 creme/lait",
      "Testé avec 83/17 creme/lait (15% sucre, 17% jaune oeuf)"
    ]
  }
}

=== ktung/cookbook/old/src/assets/recipes/200-challah.json
{
  "$schema": "./schema.json",
  "name": {
    "en": "200 - Challah",
    "fr": "200 - Challah"
  },
  "ingredients": [
    {
      "name": "allPurposeFlour",
      "bakerPercentage": 100
    },
    {
      "name": "activeDryYeast",
      "bakerPercentage": 0.6
    },
    {
      "name": "honey",
      "bakerPercentage": 18.8
    },
    {
      "name": "salt",
      "bakerPercentage": 1.8
    },
    {
      "name": "egg",
      "bakerPercentage": 16.6
    },
    {
      "name": "water",
      "bakerPercentage": 28.3
    },
    {
      "name": "oliveOil",
      "bakerPercentage": 12.5
    }
  ],
  "presetTotalIngredient": 1073,
  "notes": {
    "fr": ["Sponge : 100% levure, 100% eau + Ã©quivalent farine"]
  }
}

=== ktung/cookbook/old/src/assets/recipes/100-canneles.json
{
  "$schema": "./schema.json",
  "name": {
    "en": "100 - Canneles",
    "fr": "100 - Cannelés"
  },
  "ingredients": [
    {
      "name": "milk",
      "bakerPercentage": 100
    },
    {
      "name": "butter",
      "bakerPercentage": 10
    },
    {
      "name": "vanillaExtract",
      "bakerPercentage": 3
    },
    {
      "name": "egg",
      "bakerPercentage": 20
    },
    {
      "name": "eggYolk",
      "bakerPercentage": 8
    },
    {
      "name": "allPurposeFlour",
      "bakerPercentage": 20
    },
    {
      "name": "whiteSugar",
      "bakerPercentage": 36
    },
    {
      "name": "rhum",
      "bakerPercentage": 5
    }
  ],
  "presetTotalIngredient": 1010,
  "notes": {
    "fr": ["1 cannelés ~= 58g"]
  }
}

=== ktung/cookbook/old/src/assets/recipes/100-pate-brisee.json
{
  "$schema": "./schema.json",
  "name": {
    "en": "100 - Pate brisee",
    "fr": "100 - Pate brisee"
  },
  "ingredients": [
    {
      "name": "allPurposeFlour",
      "bakerPercentage": 100
    },
    {
      "name": "eggYolk",
      "bakerPercentage": 9
    },
    {
      "name": "water",
      "bakerPercentage": 18
    },
    {
      "name": "salt",
      "bakerPercentage": 3.65
    },
    {
      "name": "butter",
      "bakerPercentage": 45.5
    }
  ],
  "presetTotalIngredient": 388,
  "notes": {
    "fr": [
      "~1 cercle 24cm 4mm Ã©paisseur"
    ]
  }
}
