=== ktung/cookbook/old/src/assets/recipes/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "http://example.com/example.json",
  "title": "Root Schema",
  "type": "object",
  "default": {},
  "required": ["name", "ingredients", "presetTotalIngredient", "notes"],
  "properties": {
    "name": {
      "title": "The name Schema",
      "type": "object",
      "default": {},
      "required": ["en", "fr"],
      "properties": {
        "en": {
          "title": "The en Schema",
          "type": "string",
          "default": "",
          "examples": ["100 - Burger buns"]
        },
        "fr": {
          "title": "The fr Schema",
          "type": "string",
          "default": "",
          "examples": ["100 - Pains burger"]
        }
      },
      "examples": [
        {
          "en": "100 - Burger buns",
          "fr": "100 - Pains burger"
        }
      ]
    },
    "ingredients": {
      "title": "The ingredients Schema",
      "type": "array",
      "default": [],
      "items": {
        "title": "A Schema",
        "type": "object",
        "required": ["name", "bakerPercentage"],
        "properties": {
          "name": {
            "title": "The name Schema",
            "type": "string",
            "examples": [
              "allPurposeFlour",
              "activeDryYeast",
              "salt",
              "brownSugar",
              "egg",
              "oatMilk",
              "water",
              "butter"
            ]
          },
          "bakerPercentage": {
            "title": "The bakerPercentage Schema",
            "type": ["integer", "number"],
            "examples": [100, 1.6, 1.8, 3, 10, 6, 40]
          }
        },
        "examples": [
          {
            "name": "allPurposeFlour",
            "bakerPercentage": 100
          },
          {
            "name": "activeDryYeast",
            "bakerPercentage": 1.6
          },
          {
            "name": "salt",
            "bakerPercentage": 1.8
          },
          {
            "name": "brownSugar",
            "bakerPercentage": 3
          },
          {
            "name": "egg",
            "bakerPercentage": 10
          },
          {
            "name": "oatMilk",
            "bakerPercentage": 6
          },
          {
            "name": "water",
            "bakerPercentage": 40
          },
          {
            "name": "butter",
            "bakerPercentage": 10
          }
        ]
      },
      "examples": [
        [
          {
            "name": "allPurposeFlour",
            "bakerPercentage": 100
          },
          {
            "name": "activeDryYeast",
            "bakerPercentage": 1.6
          },
          {
            "name": "salt",
            "bakerPercentage": 1.8
          },
          {
            "name": "brownSugar",
            "bakerPercentage": 3
          },
          {
            "name": "egg",
            "bakerPercentage": 10
          },
          {
            "name": "oatMilk",
            "bakerPercentage": 6
          },
          {
            "name": "water",
            "bakerPercentage": 40
          },
          {
            "name": "butter",
            "bakerPercentage": 10
          }
        ]
      ]
    },
    "presetTotalIngredient": {
      "title": "The presetTotalIngredient Schema",
      "type": "integer",
      "default": 0,
      "examples": [862]
    },
    "notes": {
      "title": "The notes Schema",
      "type": "object",
      "default": {},
      "required": [],
      "properties": {
        "fr": {
          "title": "The fr Schema",
          "type": "array",
          "default": [],
          "items": {
            "title": "A Schema",
            "type": "string",
            "default": "",
            "examples": ["1 pain ~= 110g"]
          },
          "examples": [["1 pain ~= 110g"]]
        }
      },
      "examples": [
        {
          "fr": ["1 pain ~= 110g"]
        }
      ]
    }
  },
  "examples": [
    {
      "name": {
        "en": "100 - Burger buns",
        "fr": "100 - Pains burger"
      },
      "ingredients": [
        {
          "name": "allPurposeFlour",
          "bakerPercentage": 100
        },
        {
          "name": "activeDryYeast",
          "bakerPercentage": 1.6
        },
        {
          "name": "salt",
          "bakerPercentage": 1.8
        },
        {
          "name": "brownSugar",
          "bakerPercentage": 3
        },
        {
          "name": "egg",
          "bakerPercentage": 10
        },
        {
          "name": "oatMilk",
          "bakerPercentage": 6
        },
        {
          "name": "water",
          "bakerPercentage": 40
        },
        {
          "name": "butter",
          "bakerPercentage": 10
        }
      ],
      "presetTotalIngredient": 862,
      "notes": {
        "fr": ["1 pain ~= 110g"]
      }
    }
  ]
}

=== ktung/cookbook/old/src/assets/recipes/100-bao-dough.json
{
  "$schema": "./schema.json",
  "name": {
    "en": "100 - Bao Dough",
    "fr": "100 - Pate Ã  bao"
  },
  "ingredients": [
    {
      "name": "allPurposeFlour",
      "bakerPercentage": 100
    },
    {
      "name": "water",
      "bakerPercentage": 50
    },
    {
      "name": "activeDryYeast",
      "bakerPercentage": 1
    },
    {
      "name": "bakingPowder",
      "bakerPercentage": 1
    },
    {
      "name": "whiteSugar",
      "bakerPercentage": 6
    }
  ],
  "presetTotalIngredient": 790,
  "notes": {
    "fr": ["1 bao ~= 66g"]
  }
}

=== ktung/cookbook/old/src/assets/recipes/100-white-bread.json
{
  "$schema": "./schema.json",
  "name": {
    "en": "100 - White bread",
    "fr": "100 - Pain courant"
  },
  "ingredients": [
    {
      "name": "allPurposeFlour",
      "bakerPercentage": 100
    },
    {
      "name": "water",
      "bakerPercentage": 64
    },
    {
      "name": "activeDryYeast",
      "bakerPercentage": 0.5
    },
    {
      "name": "salt",
      "bakerPercentage": 1.8
    }
  ],
  "presetTotalIngredient": 832,
  "notes": {
    "fr": [
      "1 baguette ~= 250g cuit"
    ]
  }
}

=== ktung/cookbook/old/src/assets/recipes/100-moelleux-chocolat.json
{
  "$schema": "./schema.json",
  "name": {
    "en": "100 - Chocolate cake",
    "fr": "100 - Moelleux chocolat"
  },
  "ingredients": [
    {
      "name": "darkChocolate",
      "bakerPercentage": 100
    },
    {
      "name": "butter",
      "bakerPercentage": 80
    },
    {
      "name": "egg",
      "bakerPercentage": 100
    },
    {
      "name": "brownSugar",
      "bakerPercentage": 80
    },
    {
      "name": "allPurposeFlour",
      "bakerPercentage": 30
    },
    {
      "name": "salt",
      "bakerPercentage": 2
    }
  ],
  "presetTotalIngredient": 392,
  "notes": {
    "fr": [
      "Faire fondre le chocolat et le beurre",
      "Blanchir les oeufs",
      "Ajouter le mélange chocolat beurre",
      "Ajouter farine et sel",
      "Diviser en 8 portions",
      "Cuisson 10mins 180°C ventilé"
    ]
  }
}
